

# Get all users
GET http://localhost:3100/users

###
GET http://localhost:3100/users/123

### 
# Post request to create a new user
POST http://localhost:3100/users
Content-Type: application/json

{}

### 
