

# Get all users
GET http://localhost:3100/users

###
GET http://localhost:3100/users/123
?limit=10
&page=20

### 
# Post request to create a new user
POST http://localhost:3100/users
Content-Type: application/json

{
    "name": "Sayed",
    "surname": "Hossain",
    "email": "example@mail.com",
    "password": "Abc#bd23"
}

### 
